name: EsscentualAlchemy
favicon: null
layout_spectrum: 0.5508917595725507
typography_spectrum: 0.4492335021495819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7278236446436495
  lightness: 0.46536670345813036
  saturation: 0.7727845162153244
  rhythmicContrast: 0.16376936854794621
purpose: []
