name: EsscentualAlchemy
favicon: null
layout_spectrum: 0.50465
typography_spectrum: 1
title: Esscentual Alchemy natural botanical perfume - I compose Music for your Nose
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#2a2a2a'
    - '#797979'
    - '#b3b3b3'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
