name: EsscentualAlchemy
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Esscentual Alchemy natural botanical perfume - I compose Music for your Nose
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#c2c2c2'
    - '#313131'
    - '#5e5e5e'
    - '#fbfbfb'
  brandStrength: 0.0625
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
