title: Esscentual Alchemy natural botanical perfume - I compose Music for your Nose
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.625
  brandStrength: 1
  lightness: 0.375
  brandColors:
    - '#FDFDFD'
    - '#231009'
    - '#CCCCCC'
    - '#777777'
    - '#414141'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: EsscentualAlchemy
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 1
layout_spectrum: 0.5531197
